export function OpportunityDashboard({ profile, savedCount, appliedCount, onBrowse, onSaved }) {
  const nextStep = savedCount < 2 ? 'Save two opportunities' : appliedCount < 1 ? 'Apply to your first opportunity' : 'Keep your momentum going'
  const progress = Math.min(100, 22 + savedCount * 24 + appliedCount * 30)
  return <section className="opportunity-dashboard" aria-label="Your opportunity dashboard">
    <div className="dashboard-welcome"><p className="eyebrow"><span /> YOUR MOMENTUM</p><h2>Small moves.<br /><em>Real momentum.</em></h2><p>{nextStep}. Your {profile.label.toLowerCase()} board gets sharper with every action.</p><button onClick={onBrowse}>Browse opportunities →</button></div>
    <div className="dashboard-goals"><div className="goal-heading"><span className="profile-emblem">{profile.icon}</span><span><b>DevBoard path</b><small>Made for your next good move</small></span><strong>{progress}%</strong></div><div className="path-progress" aria-label={`${progress}% of your path complete`}><i style={{ width: `${progress}%` }} /></div><div className="goal-list"><button onClick={onBrowse} className="goal complete"><span>✓</span><p><b>Set your direction</b><small>{profile.label} path selected</small></p></button><button onClick={onSaved} className={savedCount >= 2 ? 'goal complete' : 'goal'}><span>{savedCount >= 2 ? '✓' : '2'}</span><p><b>Build a short list</b><small>{savedCount}/2 opportunities saved</small></p></button><button onClick={onBrowse} className={appliedCount ? 'goal complete' : 'goal'}><span>{appliedCount ? '✓' : '3'}</span><p><b>Take your first shot</b><small>{appliedCount ? `${appliedCount} application${appliedCount > 1 ? 's' : ''} started` : 'Register for one opportunity'}</small></p></button></div></div>
    <div className="dashboard-stats"><div><b>{savedCount}</b><span>Saved</span></div><div><b>{appliedCount}</b><span>Applied</span></div><div><b>2K</b><span>Live now</span></div><p>Thoughtfully curated events, challenges, and rooms where useful things happen.</p></div>
  </section>
}
