import { useState } from 'react'
import { Icon } from './Icon'

const completedAchievement = (title, note, icon) => ({ title, note, icon, unlocked: true })
const daysUntil = (value) => Math.max(0, Math.ceil((new Date(value).getTime() - Date.now()) / 86400000))
const timeLeftLabel = (event) => {
  const days = daysUntil(event.date)
  if (days === 0) return 'Happening today'
  if (days === 1) return '1 day to go'
  return `${days} days to go`
}

export function ProfilePage({ profile, user, savedEvents, appliedEvents, onBack, onEditExperience, onOpenEvent, onUpdateUser }) {
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(user)
  const achievements = [
    completedAchievement('DevBoard joined', 'Your opportunity map is ready.', '✦'),
    savedEvents.length ? completedAchievement('Opportunity scout', `${savedEvents.length} opportunity${savedEvents.length > 1 ? 'ies' : 'y'} saved for later.`, '⌁') : { title: 'Opportunity scout', note: 'Save your first opportunity to unlock.', icon: '⌁', unlocked: false },
    appliedEvents.length ? completedAchievement('First move', `${appliedEvents.length} application${appliedEvents.length > 1 ? 's' : ''} started.`, '↗') : { title: 'First move', note: 'Register for an opportunity to unlock.', icon: '↗', unlocked: false },
    appliedEvents.length >= 3 ? completedAchievement('Momentum maker', 'You have three active opportunities.', '◌') : { title: 'Momentum maker', note: `${Math.max(0, 3 - appliedEvents.length)} more application${3 - appliedEvents.length === 1 ? '' : 's'} to unlock.`, icon: '◌', unlocked: false },
  ]
  const completion = Math.min(100, 54 + (user.bio ? 15 : 0) + (user.skills ? 15 : 0) + (appliedEvents.length ? 16 : 0))
  const saveProfile = (event) => { event.preventDefault(); onUpdateUser(draft); setEditing(false) }
  return <main className="profile-page"><section className="profile-hero"><button className="back-button" onClick={onBack}><Icon name="arrow" size={16} /> Back to board</button><div className="profile-identity"><div className="avatar">{user.name.slice(0, 1).toUpperCase()}</div><div><p className="eyebrow"><span /> DEVBOARD PROFILE</p><h1>{user.name}</h1><p>{user.headline}</p><div className="profile-location"><Icon name="pin" size={14} />{user.location}<i /> <span className="availability"><b />Open to opportunities</span></div></div></div><div className="profile-actions"><button onClick={() => { setDraft(user); setEditing(true) }}>Edit profile</button><button className="primary" onClick={onEditExperience}>Change experience</button></div></section>
    <section className="profile-layout"><div className="profile-main"><section className="about-card"><div className="card-heading"><div><p className="eyebrow">ABOUT</p><h2>Your career snapshot</h2></div><span>{completion}% complete</span></div><div className="profile-progress"><i style={{ width: `${completion}%` }} /></div><p>{user.bio || 'Add a short summary so collaborators and organisers can understand what you are curious about.'}</p><div className="skill-list">{(user.skills || '').split(',').filter(Boolean).map((skill) => <span key={skill}>{skill.trim()}</span>)}</div></section>
      <section className="activity-card"><div className="card-heading"><div><p className="eyebrow">ACTIVITY</p><h2>Opportunities in motion</h2></div></div><div className="activity-tabs"><div><b>{appliedEvents.length}</b><span>Registrations confirmed</span></div><div><b>{savedEvents.length}</b><span>Saved to revisit</span></div><div><b>{achievements.filter((achievement) => achievement.unlocked).length}</b><span>Achievements unlocked</span></div></div><div className="opportunity-status-list">{[...appliedEvents.map((event) => ({ event, status: timeLeftLabel(event), className: 'applied' })), ...savedEvents.filter((event) => !appliedEvents.some((applied) => applied.id === event.id)).map((event) => ({ event, status: 'Saved for later', className: 'saved' }))].slice(0, 5).map(({ event, status, className }) => <button key={event.id} onClick={() => onOpenEvent(event)}><span className={`status-art ${event.visual}`} /><p><b>{event.title}</b><small>{event.category} · {event.mode}</small></p><em className={className}>{status}</em><Icon name="arrow" size={15} /></button>)}{!savedEvents.length && !appliedEvents.length && <div className="empty-profile-state"><span>◎</span><p><b>Your next opportunity is waiting.</b>Save something that feels like a good fit, then it will live here.</p><button onClick={onBack}>Explore opportunities</button></div>}</div></section></div>
      <aside className="profile-side"><section className="achievements-card"><p className="eyebrow">ACHIEVEMENTS</p><h2>Proof of progress</h2><div>{achievements.map((achievement) => <article className={achievement.unlocked ? 'unlocked' : ''} key={achievement.title}><span>{achievement.icon}</span><p><b>{achievement.title}</b><small>{achievement.note}</small></p>{achievement.unlocked && <Icon name="check" size={15} />}</article>)}</div></section><section className="profile-tip"><span>✦</span><p><b>One small next step</b>Save two opportunities and register for one to make your profile more useful.</p></section></aside></section>
    {editing && <div className="modal-backdrop profile-edit-backdrop" role="presentation" onMouseDown={() => setEditing(false)}><form className="profile-edit" onSubmit={saveProfile} onMouseDown={(event) => event.stopPropagation()}><button type="button" className="modal-close" onClick={() => setEditing(false)} aria-label="Close profile editor"><Icon name="close" size={18} /></button><p className="eyebrow">PROFILE SETTINGS</p><h2>Make this feel like you.</h2><label>Name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required /></label><label>Headline<input value={draft.headline} onChange={(event) => setDraft({ ...draft, headline: event.target.value })} required /></label><label>Location<input value={draft.location} onChange={(event) => setDraft({ ...draft, location: event.target.value })} required /></label><label>Skills <small>Separate with commas</small><input value={draft.skills} onChange={(event) => setDraft({ ...draft, skills: event.target.value })} /></label><label>About you<textarea value={draft.bio} onChange={(event) => setDraft({ ...draft, bio: event.target.value })} rows="3" /></label><button className="register-button" type="submit">Save profile <Icon name="check" size={16} /></button></form></div>}</main>
}
